#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["python-docx>=1.1", "reportlab>=4.0"]
# ///
"""
CV pipeline for mi-portafolio.

    cv/input/cv-data.json  ->  cv/output/HV_*.pdf|docx               (local CV files, web downloads)
                           ->  packages/core/src/data/cv-data.generated.json  (data rendered by the web)

The input JSON is the only file edited by hand (from chat with Copilot/Cursor or by
passing another JSON with the same shape). The web never edits CV data; it renders
the generated JSON and serves cv/output (synced by scripts/hv/sync-cv-downloads.mjs).

Usage:
    pnpm generate:cv
    uv run scripts/hv/generate-cv-pdf.py [path/to/other-input.json]
"""

from __future__ import annotations

import copy
import hashlib
import json
import sys
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
INPUT_JSON = REPO_ROOT / "cv/input/cv-data.json"
OUTPUT_DIR = REPO_ROOT / "cv/output"
WEB_DATA_JSON = REPO_ROOT / "packages/core/src/data/cv-data.generated.json"
PUBLIC_DIR = REPO_ROOT / "apps/web/public"

OUTPUT_FILES = {
    "HV_2026_2_ATS_AndresRodriguez.pdf": ("pdf", False),
    "HV_2026_2_Visual_AndresRodriguez.pdf": ("pdf", True),
    "HV_2026_2_ATS_AndresRodriguez.docx": ("docx", False),
    "HV_2026_2_Visual_AndresRodriguez.docx": ("docx", True),
}

REQUIRED_TEXT = ("name", "title", "email", "phone1", "phone2", "location", "linkedin", "github", "portfolio", "profile")
REQUIRED_LISTS = ("skills", "experience", "education", "officialCertifications", "learningPathsCertifications", "languages")
DERIVED_KEYS = ("certificates", "_meta")

PRIMARY = HexColor("#1F4E79")
ACCENT = HexColor("#2E75B6")
TEXT = HexColor("#1A1A1A")
MUTED = HexColor("#555555")
LIGHT = HexColor("#F3F7FB")

PRIMARY_RGB = RGBColor(0x1F, 0x4E, 0x79)
ACCENT_RGB = RGBColor(0x2E, 0x75, 0xB6)
TEXT_RGB = RGBColor(0x1A, 0x1A, 0x1A)


# ───────────────────────────── INPUT ─────────────────────────────


def input_digest(path: Path) -> str:
    """Line-ending independent hash so Windows (CRLF) and CI (LF) checkouts agree."""
    return hashlib.sha256(path.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


def _iter_courses(data: dict):
    for category, courses in data.get("certificatesByCategory", {}).items():
        for course in courses:
            yield f"certificatesByCategory.{category}", course
    for course in data.get("learningPathsCertifications", []):
        yield "learningPathsCertifications", course
    for cert in data.get("officialCertifications", []):
        yield "officialCertifications", cert


def validate(data: dict) -> list[str]:
    errors: list[str] = []
    for key in REQUIRED_TEXT:
        if not isinstance(data.get(key), str) or not data[key].strip():
            errors.append(f"'{key}' must be a non-empty string")
    for key in REQUIRED_LISTS:
        if not isinstance(data.get(key), list) or not data[key]:
            errors.append(f"'{key}' must be a non-empty list")
    if not isinstance(data.get("certificatesByCategory"), dict) or not data["certificatesByCategory"]:
        errors.append("'certificatesByCategory' must be a non-empty object of category -> courses")
    for key in DERIVED_KEYS:
        if key in data:
            errors.append(f"'{key}' is generated by Python; remove it from the input")

    for i, skill in enumerate(data.get("skills", [])):
        if not skill.get("category") or not skill.get("items"):
            errors.append(f"skills[{i}] needs 'category' and 'items'")
    for i, exp in enumerate(data.get("experience", [])):
        missing = [k for k in ("company", "role", "period", "bullets") if not exp.get(k)]
        if missing:
            errors.append(f"experience[{i}] is missing {missing}")
    for i, edu in enumerate(data.get("education", [])):
        missing = [k for k in ("degree", "institution", "year") if not edu.get(k)]
        if missing:
            errors.append(f"education[{i}] is missing {missing}")

    seen: dict[str, str] = {}
    for where, course in _iter_courses(data):
        title = course.get("title")
        if not title:
            errors.append(f"{where}: every entry needs a 'title'")
            continue
        if title in seen:
            errors.append(f"'{title}' is duplicated ({seen[title]} and {where})")
        seen[title] = where
        hours = course.get("hours")
        if hours is not None and (not isinstance(hours, int) or hours < 0):
            errors.append(f"'{title}': 'hours' must be a non-negative integer")
        file_path = course.get("filePath")
        if file_path and not (PUBLIC_DIR / file_path.lstrip("/")).is_file():
            errors.append(f"'{title}': file not found apps/web/public{file_path}")
    return errors


def build_web_data(data: dict, digest: str) -> dict:
    """Input + derived fields rendered by the web (flat certificate list for the carousel)."""
    web = copy.deepcopy(data)
    certificates = [
        {"title": f'{cert["title"]} — {cert["issuer"]}', "filePath": cert.get("filePath")}
        for cert in data["officialCertifications"]
    ]
    certificates += [
        {"title": course["title"], "filePath": course.get("filePath")}
        for course in data["learningPathsCertifications"]
    ]
    certificates += [
        {"title": course["title"], "filePath": course.get("filePath")}
        for courses in data["certificatesByCategory"].values()
        for course in courses
    ]
    web["certificates"] = certificates
    web["_meta"] = {
        "generatedBy": "scripts/hv/generate-cv-pdf.py",
        "source": "cv/input/cv-data.json",
        "sourceSha256": digest,
        "note": "Generated file. Edit cv/input/cv-data.json and run `pnpm generate:cv`.",
    }
    return web


def _display_url(url: str) -> str:
    return url.removeprefix("https://").removeprefix("http://").removeprefix("www.")


def to_document_data(data: dict) -> dict:
    """Map the input (web shape) to the fields the PDF/DOCX layouts use."""
    return {
        "name": data["name"],
        "title": data["title"],
        "location": data["location"],
        "phone1": data["phone1"],
        "phone2": data["phone2"],
        "email": data["email"],
        "linkedin": _display_url(data["linkedin"]),
        "github": _display_url(data["github"]),
        "portfolio": data["portfolio"],
        "profile": data["profile"],
        "skills": [{"cat": s["category"], "items": s["items"]} for s in data["skills"]],
        "experience": [
            {"company": e["company"], "role": e["role"], "period": e["period"], "bullets": e["bullets"]}
            for e in data["experience"]
        ],
        "education": [
            {"title": e["degree"], "inst": e["institution"], "year": e["year"]} for e in data["education"]
        ],
        "officialCertifications": [
            {"title": c["title"], "issuer": c["issuer"]} for c in data["officialCertifications"]
        ],
        "learningPaths": [
            {"title": c["title"], "hours": c.get("hours")} for c in data["learningPathsCertifications"]
        ],
        "coursesByCategory": {
            category: [{"title": c["title"], "hours": c.get("hours")} for c in courses]
            for category, courses in data["certificatesByCategory"].items()
        },
        "languages": data["languages"],
    }


def format_course(course: dict) -> str:
    hours = course.get("hours")
    return f'{course["title"]} ({hours}h)' if hours else course["title"]


# ───────────────────────────── PDF ─────────────────────────────


def build_styles():
    base = getSampleStyleSheet()
    return {
        "name": ParagraphStyle(
            "CVName",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=18,
            textColor=PRIMARY,
            alignment=TA_CENTER,
            spaceAfter=4,
        ),
        "title": ParagraphStyle(
            "CVTitle",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=9,
            textColor=ACCENT,
            alignment=TA_CENTER,
            spaceAfter=4,
            leading=12,
        ),
        "contact": ParagraphStyle(
            "CVContact",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            textColor=TEXT,
            alignment=TA_CENTER,
            spaceAfter=2,
            leading=10,
        ),
        "section": ParagraphStyle(
            "CVSection",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            textColor=PRIMARY,
            spaceBefore=10,
            spaceAfter=4,
            leading=14,
        ),
        "subsection": ParagraphStyle(
            "CVSubSection",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=ACCENT,
            spaceBefore=6,
            spaceAfter=3,
        ),
        "body": ParagraphStyle(
            "CVBody",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            textColor=TEXT,
            alignment=TA_JUSTIFY,
            leading=11,
            spaceAfter=4,
        ),
        "kv": ParagraphStyle(
            "CVKeyValue",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            textColor=TEXT,
            leading=11,
            spaceAfter=2,
        ),
        "bullet": ParagraphStyle(
            "CVBullet",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            textColor=TEXT,
            leftIndent=12,
            leading=11,
            spaceAfter=1,
        ),
        "job": ParagraphStyle(
            "CVJob",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9.5,
            textColor=PRIMARY,
            spaceBefore=6,
            spaceAfter=1,
        ),
        "period": ParagraphStyle(
            "CVPeriod",
            parent=base["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=8,
            textColor=MUTED,
            spaceAfter=2,
        ),
        "edu": ParagraphStyle(
            "CVEdu",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=9,
            textColor=TEXT,
            spaceBefore=3,
            spaceAfter=2,
        ),
        "cat": ParagraphStyle(
            "CVCat",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            textColor=PRIMARY,
            spaceBefore=4,
            spaceAfter=1,
        ),
        "skill_cat": ParagraphStyle(
            "CVSkillCat",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            textColor=PRIMARY,
            spaceAfter=1,
        ),
        "skill_items": ParagraphStyle(
            "CVSkillItems",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=7.5,
            textColor=TEXT,
            leading=9,
        ),
    }


def section_rule(styles, title: str):
    return Paragraph(
        f'<font color="#1F4E79"><b>{title.upper()}</b></font>'
        f'<br/><font color="#2E75B6">{"_" * 78}</font>',
        styles["section"],
    )


def add_header(story, data, styles):
    story.append(Paragraph(data["name"], styles["name"]))
    story.append(Paragraph(data["title"], styles["title"]))
    story.append(
        Paragraph(
            f'{data["location"]}  |  {data["phone1"]}  |  {data["phone2"]}',
            styles["contact"],
        )
    )
    story.append(
        Paragraph(
            f'{data["email"]}  |  {data["linkedin"]}  |  {data["github"]}',
            styles["contact"],
        )
    )
    story.append(
        Paragraph(
            f'Portafolio: <font color="#2E75B6">{data["portfolio"]}</font>',
            styles["contact"],
        )
    )
    story.append(Spacer(1, 6))


def add_education_and_certs_pdf(story, data, styles):
    story.append(section_rule(styles, "Educación"))
    for edu in data["education"]:
        story.append(
            Paragraph(
                f'<b><font color="#1F4E79">{edu["title"]}</font></b>'
                f'  —  {edu["inst"]}  ({edu["year"]})',
                styles["edu"],
            )
        )

    story.append(section_rule(styles, "Certificaciones & Formación"))

    story.append(Paragraph("Certificaciones Oficiales", styles["subsection"]))
    for cert in data["officialCertifications"]:
        story.append(Paragraph(f'- {cert["title"]} — {cert["issuer"]}', styles["bullet"]))

    story.append(Paragraph("Rutas de Aprendizaje", styles["subsection"]))
    for course in data["learningPaths"]:
        story.append(Paragraph(f"- {format_course(course)}", styles["bullet"]))

    story.append(Paragraph("Cursos de Formación", styles["subsection"]))
    for category, courses in data["coursesByCategory"].items():
        story.append(Paragraph(category, styles["cat"]))
        for course in courses:
            story.append(Paragraph(f"- {format_course(course)}", styles["bullet"]))

    story.append(section_rule(styles, "Portafolio"))
    story.append(
        Paragraph(
            f'<b>Sitio web:</b> <font color="#2E75B6">{data["portfolio"]}</font>',
            styles["kv"],
        )
    )

    story.append(section_rule(styles, "Idiomas"))
    for lang in data["languages"]:
        story.append(
            Paragraph(
                f'<b><font color="#1F4E79">{lang["lang"]}:</font></b> {lang["level"]}',
                styles["kv"],
            )
        )


def build_ats_pdf(data, output_path: Path):
    styles = build_styles()
    story = []
    add_header(story, data, styles)

    story.append(section_rule(styles, "Perfil Profesional"))
    story.append(Paragraph(data["profile"], styles["body"]))

    story.append(section_rule(styles, "Competencias Técnicas"))
    for skill in data["skills"]:
        story.append(
            Paragraph(
                f'<b><font color="#1F4E79">{skill["cat"]}:</font></b> {skill["items"]}',
                styles["kv"],
            )
        )

    story.append(section_rule(styles, "Experiencia Profesional"))
    for exp in data["experience"]:
        story.append(
            Paragraph(
                f'{exp["company"]}  —  {exp["role"]}    '
                f'<font color="#555555"><i>{exp["period"]}</i></font>',
                styles["job"],
            )
        )
        for bullet in exp["bullets"]:
            story.append(Paragraph(f"- {bullet}", styles["bullet"]))

    add_education_and_certs_pdf(story, data, styles)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=0.7 * inch,
        rightMargin=0.7 * inch,
        topMargin=0.55 * inch,
        bottomMargin=0.55 * inch,
        title=f'{data["name"]} - CV ATS',
        author=data["name"],
    )
    doc.build(story)


def build_visual_pdf(data, output_path: Path):
    """Visual CV: same content as ATS with accent styling and compact skills grid."""
    styles = build_styles()
    story = []
    add_header(story, data, styles)

    story.append(section_rule(styles, "Perfil Profesional"))
    story.append(Paragraph(data["profile"], styles["body"]))

    story.append(section_rule(styles, "Competencias Técnicas"))
    for skill in data["skills"]:
        story.append(
            Paragraph(
                f'<b><font color="#1F4E79">{skill["cat"]}:</font></b> {skill["items"]}',
                styles["kv"],
            )
        )

    story.append(section_rule(styles, "Experiencia Profesional"))
    for exp in data["experience"]:
        story.append(Paragraph(f'{exp["company"]}  —  {exp["role"]}', styles["job"]))
        story.append(Paragraph(exp["period"], styles["period"]))
        for bullet in exp["bullets"]:
            story.append(Paragraph(f"- {bullet}", styles["bullet"]))

    add_education_and_certs_pdf(story, data, styles)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=0.6 * inch,
        rightMargin=0.6 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.5 * inch,
        title=f'{data["name"]} - CV Visual',
        author=data["name"],
    )
    doc.build(story)


# ───────────────────────────── DOCX ─────────────────────────────


def _set_run(run, *, bold=False, size=10, color=TEXT_RGB, italic=False):
    run.bold = bold
    run.italic = italic
    run.font.size = Pt(size)
    run.font.color.rgb = color


def _add_bottom_border(paragraph):
    p = paragraph._p
    pPr = p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "12")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "2E75B6")
    pBdr.append(bottom)
    pPr.append(pBdr)


def add_section_title_docx(doc: Document, text: str):
    p = doc.add_paragraph()
    run = p.add_run(text.upper())
    _set_run(run, bold=True, size=12, color=PRIMARY_RGB)
    p.paragraph_format.space_before = Pt(10)
    p.paragraph_format.space_after = Pt(4)
    _add_bottom_border(p)


def add_subsection_docx(doc: Document, text: str):
    p = doc.add_paragraph()
    run = p.add_run(text)
    _set_run(run, bold=True, size=11, color=ACCENT_RGB)
    p.paragraph_format.space_before = Pt(8)
    p.paragraph_format.space_after = Pt(3)


def add_bullet_docx(doc: Document, text: str):
    p = doc.add_paragraph(style="List Bullet")
    run = p.add_run(text)
    _set_run(run, size=10, color=TEXT_RGB)


def add_education_and_certs_docx(doc: Document, data: dict):
    add_section_title_docx(doc, "Educación")
    for edu in data["education"]:
        p = doc.add_paragraph()
        r1 = p.add_run(edu["title"])
        _set_run(r1, bold=True, size=10.5, color=PRIMARY_RGB)
        r2 = p.add_run(f'  —  {edu["inst"]}  ({edu["year"]})')
        _set_run(r2, size=10, color=TEXT_RGB)

    add_section_title_docx(doc, "Certificaciones & Formación")

    add_subsection_docx(doc, "Certificaciones Oficiales")
    for cert in data["officialCertifications"]:
        add_bullet_docx(doc, f'{cert["title"]} — {cert["issuer"]}')

    add_subsection_docx(doc, "Rutas de Aprendizaje")
    for course in data["learningPaths"]:
        add_bullet_docx(doc, format_course(course))

    add_subsection_docx(doc, "Cursos de Formación")
    for category, courses in data["coursesByCategory"].items():
        p = doc.add_paragraph()
        run = p.add_run(category)
        _set_run(run, bold=True, size=10, color=PRIMARY_RGB)
        for course in courses:
            add_bullet_docx(doc, format_course(course))

    add_section_title_docx(doc, "Portafolio")
    p = doc.add_paragraph()
    r1 = p.add_run("Sitio web: ")
    _set_run(r1, bold=True, size=10, color=PRIMARY_RGB)
    r2 = p.add_run(data["portfolio"])
    _set_run(r2, size=10, color=ACCENT_RGB)

    add_section_title_docx(doc, "Idiomas")
    for lang in data["languages"]:
        p = doc.add_paragraph()
        r1 = p.add_run(f'{lang["lang"]}: ')
        _set_run(r1, bold=True, size=10, color=PRIMARY_RGB)
        r2 = p.add_run(lang["level"])
        _set_run(r2, size=10, color=TEXT_RGB)


def build_docx(data: dict, output_path: Path, visual: bool = False):
    doc = Document()
    for section in doc.sections:
        section.top_margin = Pt(54)
        section.bottom_margin = Pt(54)
        section.left_margin = Pt(54 if visual else 60)
        section.right_margin = Pt(54 if visual else 60)

    name = doc.add_paragraph()
    name.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = name.add_run(data["name"])
    _set_run(r, bold=True, size=18, color=PRIMARY_RGB)

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = title.add_run(data["title"])
    _set_run(r, size=10, color=ACCENT_RGB)

    for line in (
        f'{data["location"]}  |  {data["phone1"]}  |  {data["phone2"]}',
        f'{data["email"]}  |  {data["linkedin"]}  |  {data["github"]}',
        f'Portafolio: {data["portfolio"]}',
    ):
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.add_run(line)
        _set_run(r, size=9, color=TEXT_RGB if "Portafolio" not in line else ACCENT_RGB)

    add_section_title_docx(doc, "Perfil Profesional")
    p = doc.add_paragraph()
    r = p.add_run(data["profile"])
    _set_run(r, size=10, color=TEXT_RGB)

    add_section_title_docx(doc, "Competencias Técnicas")
    for skill in data["skills"]:
        p = doc.add_paragraph()
        r1 = p.add_run(f'{skill["cat"]}: ')
        _set_run(r1, bold=True, size=10, color=PRIMARY_RGB)
        r2 = p.add_run(skill["items"])
        _set_run(r2, size=10, color=TEXT_RGB)

    add_section_title_docx(doc, "Experiencia Profesional")
    for exp in data["experience"]:
        p = doc.add_paragraph()
        r1 = p.add_run(f'{exp["company"]}  —  {exp["role"]}')
        _set_run(r1, bold=True, size=11, color=PRIMARY_RGB)
        p2 = doc.add_paragraph()
        r2 = p2.add_run(exp["period"])
        _set_run(r2, size=9, color=MUTED if False else RGBColor(0x55, 0x55, 0x55), italic=True)
        for bullet in exp["bullets"]:
            add_bullet_docx(doc, bullet)

    add_education_and_certs_docx(doc, data)
    doc.save(str(output_path))


def write_outputs(doc_data: dict) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for filename, (kind, visual) in OUTPUT_FILES.items():
        path = OUTPUT_DIR / filename
        if kind == "pdf":
            (build_visual_pdf if visual else build_ats_pdf)(doc_data, path)
        else:
            build_docx(doc_data, path, visual=visual)
        print(f"✅ {path.relative_to(REPO_ROOT).as_posix()}")


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) >= 2 else INPUT_JSON
    if not input_path.is_file():
        print(f"❌ Input not found: {input_path}")
        return 1

    data = json.loads(input_path.read_text(encoding="utf-8"))
    errors = validate(data)
    if errors:
        print(f"❌ {input_path.name} has {len(errors)} problem(s):")
        for error in errors:
            print(f"   - {error}")
        return 1

    if input_path != INPUT_JSON:
        INPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
        INPUT_JSON.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"✅ {INPUT_JSON.relative_to(REPO_ROOT).as_posix()} (copied from {input_path.name})")

    write_outputs(to_document_data(data))

    web_data = build_web_data(data, input_digest(INPUT_JSON))
    WEB_DATA_JSON.write_text(json.dumps(web_data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"✅ {WEB_DATA_JSON.relative_to(REPO_ROOT).as_posix()}")

    print("\n🎉 CV regenerated. The web picks up cv/output on the next `pnpm dev` / `pnpm build`.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
